title: Happy Birthday Koala Bear
author: Your only bear
email: gargakash514@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I Hope, You are doing well Where do I start our journey whether from the versy first day I saw you or the day I feel for you something. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  gargakash514 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
